#!/bin/bash

## Entitlement key
export ENTITLEMENT_KEY=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJJQk0gTWFya2V0cGxhY2UiLCJpYXQiOjE2NDc0MzIyNTEsImp0aSI6ImJmZjdmZmE5MjViYjRiOGM5YzUzYjM4NWE5NTY3NmMyIn0.98aZDPwyU-5JxaDPRihXYoVJpt9nftnEizyydUVwYu0

export SUBSCRIPTION_CHANNEL_IA=v3.4
export SUBSCRIPTION_CHANNEL_IAF=v1.3
export NAMESPACE=cp4waiops
export SUBSCRIPTION_STARTINGCSV_IA=ibm-infrastructure-automation-operator.v3.4.2
export SUBSCRIPTION_STARTINGCSV_IAF=ibm-automation.v1.3.9

export STORAGE_CLASS=ibmc-file-gold-gid
export STORAGE_CLASS_LARGE_BLOCK=ibmc-block-gold

export YOUR_LDAP_USER_GROUP=imgroup